  displayName: Lights
  description: An endpoint which interacts with Light objects
  get:
    description: Returns all configured lights
    body:
      type: lights
      example: !include ../examples/lights.json
  /{lightId}:
    get:
      description: Returns the specified light
      body:
        type: light
        example: !include ../examples/light.json
    put:
      description: Attempts to update all attributes in the given light.
      body:
        type: light
        example: !include ../examples/light.json
      responses:
        200: !include types/200Response.raml
    /state:
      put:
        description: Sets the State attribute of the light
        body:
          type: state
          example: !include ../examples/state.json
        responses:
          200: !include ../types/200Response.raml
